name: Optimize resource packs
on: [push]
# This permissions section explicitly gives the workflow permission to create releases.
# Most of the time it's not needed to set it, as the default GITHUB_TOKEN permissions
# are permissive enough, but that's not always the case
permissions:
  contents: write
jobs:
  packsquash:
    name: Optimize resource packs
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Run PackSquash for Snowstorm Pack
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'snowstorm-pack'
            output_file_path = '/tmp/snowstorm-pack.zip'
            artifact_name = 'Snowstorm Pack.zip'
      - name: Run PackSquash for Nexus Pack
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'nexus-pack'
            output_file_path = '/tmp/nexus-pack.zip'
            artifact_name = 'Nexus Pack.zip'
      - name: Tag and create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: action-v${{ github.run_number }}
          files: |
            /tmp/snowstorm-pack.zip
            /tmp/nexus-pack.zip